### ISSUE TITLE
[8] Wireframe - Homepage

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#10]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/141246156-8b566f44-76b5-44fb-a9df-9e97b4b3d560.png)
![image](https://user-images.githubusercontent.com/91137692/141246206-a9f5802d-46d5-4ed7-bd69-732fef4addab.png)
![image](https://user-images.githubusercontent.com/91137692/141246359-72433ed6-c027-404f-aa05-d972f9585569.png)
![image](https://user-images.githubusercontent.com/91137692/141246436-a83b053a-c1a2-4d39-8091-87dc0f8e4f84.png)
