### ISSUE TITLE
[8] HTML & CSS - Developer's Page from Other's POV

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#107]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/151728586-21f0fd71-7c03-427c-a5a7-49eed0e5347a.png)
![image](https://user-images.githubusercontent.com/91137692/151728605-58694a91-6126-4e7c-9806-f5bde86fec2c.png)
