### ISSUE TITLE
[2] Wireframe - Log in 

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#12]

**Comment by DGLjhey** [comment]
![Log in final](https://user-images.githubusercontent.com/91172842/141283242-c694f40e-7430-48fc-9c5e-2f180936f9ee.PNG)

**Comment by DGLjhey** [comment]
![log in - full screen](https://user-images.githubusercontent.com/91172842/141629206-56e6eb0f-71b8-4aff-849e-06fda1af5577.PNG)

**Comment by DGLjhey** [comment]
![log in - pop up](https://user-images.githubusercontent.com/91172842/141629348-c3ef364d-0e19-4fc0-bb7f-d1257fa02c3e.PNG)

**Comment by DGLjhey** [comment]
![messaging design 1](https://user-images.githubusercontent.com/91172842/141629514-98022369-a780-4f47-aa45-5e9f6593ab55.PNG)

**Comment by DGLjhey** [comment]
![new log in](https://user-images.githubusercontent.com/91172842/141987017-8f5850d3-ad57-4845-8427-46f6f51595f8.PNG)
