### ISSUE TITLE
[8] Wireframe - Add user

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#15]

**Comment by Yaksha05** [comment]
![Add User (1)](https://user-images.githubusercontent.com/91130566/141758256-3b2dac29-36fc-4e89-abd4-d6273e9d22cc.jpg)
![Add User (2)](https://user-images.githubusercontent.com/91130566/141758261-8d5f1d40-f1b6-4095-8e3f-aae6db3ba9df.jpg)
