### ISSUE TITLE
[5] Wireframe - Order

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#17]

**Comment by mjhlcsplln** [comment]
![0003](https://user-images.githubusercontent.com/73598463/141279689-17b93167-9d2d-4f4d-a1cf-8fef06bff49a.jpg)
![0002](https://user-images.githubusercontent.com/73598463/141279701-5d426b82-6dfd-4142-91ea-0646523fff40.jpg)
![0001](https://user-images.githubusercontent.com/73598463/141279707-23e2cc75-6e09-4e8f-b7cf-98d0e2f26f3e.jpg)

**Comment by mjhlcsplln** [comment]
![1111_page-0001](https://user-images.githubusercontent.com/73598463/141285220-46d71cc7-7152-409c-83b4-a62d2cd91e74.jpg)
![2222_page-0001](https://user-images.githubusercontent.com/73598463/141285284-c90f6f08-ad2e-42f1-ad94-3263510e3cd6.jpg)
![3333_page-0001](https://user-images.githubusercontent.com/73598463/141285277-c5e51fa6-13dd-422a-a455-557745afca52.jpg)

Desktop Version for Wireframe of Order

**Comment by mjhlcsplln** [comment]
![1111_page-0001](https://user-images.githubusercontent.com/73598463/141285892-280c1a9a-ac24-49b3-9fb5-f998799fbcf1.jpg)
![22222_page-0001](https://user-images.githubusercontent.com/73598463/141285885-2e9a903a-4478-4f7c-b79a-415ba4aacd51.jpg)
![3final_page-0001](https://user-images.githubusercontent.com/73598463/141311719-3fc5249c-1840-47b7-84b9-8fcecd437121.jpg)
