### ISSUE TITLE
[5] Wireframe - Payment

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#19]

**Comment by mjhlcsplln** [comment]
![payment1_page-0001](https://user-images.githubusercontent.com/73598463/141316958-71c6895a-5d50-4713-bbbb-256d47743dbb.jpg)
![payment2_page-0002](https://user-images.githubusercontent.com/73598463/141316970-53148913-5f90-4409-a43f-2bcb67ece443.jpg)
