### ISSUE TITLE
HTML & CSS - Homepage

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#27]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/142904670-fedad62c-4f1d-411d-a3b7-3dd303b27b5a.png)

![image](https://user-images.githubusercontent.com/91137692/142904814-82a561e5-8a3f-4fe1-ac58-bfe8eec2f3bf.png)

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/142972467-cf148ae5-3973-417f-a748-60a5a9089775.png)

![image](https://user-images.githubusercontent.com/91137692/142972503-8df1f314-7c68-4793-8f9b-f10803a3707e.png)

![image](https://user-images.githubusercontent.com/91137692/142972523-d56b71a0-dd50-43df-90b5-adb83a6eda03.png)

![image](https://user-images.githubusercontent.com/91137692/142972558-25869129-7447-4711-90e2-11ab25dbd755.png)
