### ISSUE TITLE
[13] HTML & CSS - Homepage

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#38]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/144752386-f0f6e0a4-e7fd-46d5-a11c-b9bacb2587e2.png)
![image](https://user-images.githubusercontent.com/91137692/144752397-022adf30-8251-4009-afb4-1624ad84cb2e.png)
![image](https://user-images.githubusercontent.com/91137692/144752405-f8b599bc-6834-4507-b7b7-e22cc61682e5.png)
