### ISSUE TITLE
[8] HTML & CSS - Browse

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#42]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/144753516-814294a3-1917-4708-bede-6d34514ba37e.png)
![image](https://user-images.githubusercontent.com/91137692/144753529-cfd47fea-9324-46b4-8edf-5936520ecd2f.png)
![image](https://user-images.githubusercontent.com/91137692/144753538-d2840182-652e-42f4-9359-d1bf3047884a.png)
