### ISSUE TITLE
[8] - UI Improvement

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#58]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/146001170-573913f8-805c-4486-93a1-d9554ee32ca3.png)
![image](https://user-images.githubusercontent.com/91137692/146001246-a76583af-9296-4c07-91b1-447179fbd20c.png)
![image](https://user-images.githubusercontent.com/91137692/146001346-ef42b11d-bb6f-47f4-89df-52c776874956.png)
