### ISSUE TITLE
[1] - Wireframes

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#59]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/145982165-6352afe3-4bbf-417d-bd3d-977124403718.png)
![image](https://user-images.githubusercontent.com/91137692/145982223-5ca18024-2e5b-437f-b724-daea64504995.png)
![image](https://user-images.githubusercontent.com/91137692/145982344-558ad26a-eab5-4efe-80a0-4f978721dfa5.png)
![image](https://user-images.githubusercontent.com/91137692/145982428-35126e2c-336a-49bf-8837-9ca85a064cca.png)
