### ISSUE TITLE
HTML & CSS - Browse

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#72]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/148787780-2d7af583-98f3-405a-8404-586300ad49e9.png)
![image](https://user-images.githubusercontent.com/91137692/148787814-e7452e66-d2fb-4cc4-967f-355b337f99e5.png)
![image](https://user-images.githubusercontent.com/91137692/148787838-93f4b681-6a45-42cc-81ba-d096535ffbb9.png)
