### ISSUE TITLE
[13] HTML & CSS - View Specific Project

### ISSUE THREAD

**Issue by hakushakuu** [hakushakuu/TEAM04#89]

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/151727902-91ad6f50-9135-47c7-a677-4aeca55b1fa3.png)
![image](https://user-images.githubusercontent.com/91137692/151727930-140665b5-3d18-48d4-9cef-67394c04b4b1.png)

**Comment by elaineandus** [comment]
![image](https://user-images.githubusercontent.com/91137692/151728041-b1969535-4eca-4f0c-bf33-e89d2c9d7a6a.png)
![image](https://user-images.githubusercontent.com/91137692/151728058-38105b9e-7c72-4a0e-8e34-5b4200920b81.png)
